# Generated by Django 4.1.4 on 2023-06-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.CharField(max_length=100, null=True, verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=100, null=True, verbose_name='sender'),
        ),
    ]
