# Generated by Django 4.1.4 on 2023-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_chat_receiver_alter_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/image/', verbose_name='Question image'),
        ),
    ]
