# Generated by Django 4.1.4 on 2023-06-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, null=True, verbose_name='Nickname')),
                ('f_name', models.CharField(max_length=100, null=True, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='devs/photo/', verbose_name='Profile Pic')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('skill', models.CharField(blank=True, max_length=200, null=True, verbose_name='Skills')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('github', models.URLField(blank=True, null=True, verbose_name='github')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp')),
            ],
        ),
    ]
