# Generated by Django 4.1.4 on 2023-07-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_developer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['l_name']},
        ),
    ]
